---
- name: Restart Control Center
  systemd:
    daemon_reload: true
    name: "{{control_center_service_name}}"
    state: restarted
    scope: "{{ 'user' if systemd_mode == 'user' else 'system' }}"

- name: Startup Delay
  wait_for:
    timeout: "{{ control_center_health_check_delay }}"
