---
driver:
  name: docker
platforms:
  - name: zookeeper1${BUILD_NUMBER}
    hostname: zookeeper1${BUILD_NUMBER}.confluent${BUILD_NUMBER}
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${BUILD_NUMBER}
  - name: kafka-broker1${BUILD_NUMBER}
    hostname: kafka-broker1${BUILD_NUMBER}.confluent${BUILD_NUMBER}
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${BUILD_NUMBER}
  - name: schema-registry1${BUILD_NUMBER}.confluent${BUILD_NUMBER}
    hostname: schema-registry1.confluent
    groups:
      - schema_registry
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${BUILD_NUMBER}
  - name: kafka-rest1${BUILD_NUMBER}
    hostname: kafka-rest1${BUILD_NUMBER}.confluent${BUILD_NUMBER}
    groups:
      - kafka_rest
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${BUILD_NUMBER}
  - name: kafka-connect1${BUILD_NUMBER}
    hostname: kafka-connect1${BUILD_NUMBER}.confluent${BUILD_NUMBER}
    groups:
      - kafka_connect
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${BUILD_NUMBER}
  - name: ksql1${BUILD_NUMBER}
    hostname: ksql1${BUILD_NUMBER}.confluent${BUILD_NUMBER}
    groups:
      - ksql
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${BUILD_NUMBER}
  - name: control-center1${BUILD_NUMBER}
    hostname: control-center1${BUILD_NUMBER}.confluent${BUILD_NUMBER}
    groups:
      - control_center
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    published_ports:
      - "9021:9021"
    networks:
      - name: confluent${BUILD_NUMBER}
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  playbooks:
    converge: ../../../../all.yml
  inventory:
    group_vars:
      all:
        sasl_protocol: plain
        installation_method: "archive"
        kafka_connect_confluent_hub_plugins:
          - jcustenborder/kafka-connect-spooldir:2.0.43

verifier:
  name: ansible
lint: |
  set -e
  yamllint -c ../../.yamllint ../..
scenario:
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
