---
- name: Restart KSQL
  systemd:
    daemon_reload: true
    name: "{{ksql_service_name}}"
    state: restarted
    scope: "{{ 'user' if systemd_mode == 'user' else 'system' }}"

- name: Startup Delay
  wait_for:
    timeout: "{{ ksql_health_check_delay }}"
