---
- name: Restart Schema Registry
  systemd:
    daemon_reload: true
    name: "{{schema_registry_service_name}}"
    state: restarted
    scope: "{{ 'user' if systemd_mode == 'user' else 'system' }}"

- name: Startup Delay
  wait_for:
    timeout: "{{ schema_registry_health_check_delay }}"
