---
- name: Restart Zookeeper
  systemd:
    daemon_reload: true
    name: "{{zookeeper_service_name}}"
    state: restarted
    scope: "{{ 'user' if systemd_mode == 'user' else 'system' }}"

- name: Startup Delay
  wait_for:
    timeout: "{{ zookeeper_health_check_delay }}"
